version: 1

formatters:
  extended:
    format: '%(asctime)s.%(msecs)03d %(levelname)s %(module)s - %(funcName)s: %(message).1066s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: extended

loggers:
  boto3:
    level: WARN

root:
  handlers: [console]
  level: INFO
